/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;

import CONNECTION.LoadData;
import Controller.controller;
import Model.TaiKhoan;
import java.awt.event.KeyEvent;

/**
 *
 * @author Admin
 */
public class GiaoDienDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public GiaoDienDangNhap() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BaoLoi = new javax.swing.JLabel();
        txtDangNhap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cbhienMK = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setName(""); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vui lòng liên hệ Admin để được cấp quyền cao hơn ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, 500, -1));

        BaoLoi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BaoLoi.setForeground(new java.awt.Color(244, 108, 63));
        BaoLoi.setText("Thông báo:");
        getContentPane().add(BaoLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 480, 28));

        txtDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(txtDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 103, 236, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 102, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mật Khẩu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 150, 133, -1));

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangnhap.png"))); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        btnDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDangNhapKeyPressed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 229, 148, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 151, 236, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 149, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 30));

        cbhienMK.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbhienMK.setText("Hiện mật khẩu");
        cbhienMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhienMKActionPerformed(evt);
            }
        });
        getContentPane().add(cbhienMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 191, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDangNhapActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String name = txtDangNhap.getText();
        String pass = password.getText();
        LoadData.loadTableTaiKhoan();
        int index = -1;
        for (TaiKhoan tk : controller.arrayListTaiKhoan) {
            if (name.equals(tk.getMaNV().trim())) {
                index = controller.arrayListTaiKhoan.indexOf(tk);
            }
        }
        if (index == -1) {
            BaoLoi.setText("Tài khoản Không Tồn Tại");
        } else {
            TaiKhoan tk = controller.arrayListTaiKhoan.get(index);
            if (tk.getMatKhau().equals(pass)) {
                controller.tk = tk;

                if (tk.getChucVu().getMaCV().equals("1") && tk.getTrangThaiXoa()== 0) {
                     Home home = new Home();
                    home.setLocationRelativeTo(null);
                    home.setVisible(true);
                    this.dispose();

                } else if (tk.getChucVu().getMaCV().equals("2") && tk.getTrangThaiXoa()==0) {
                    Home home = new Home();
                    home.setLocationRelativeTo(null);
                    home.setVisible(true);
                    this.dispose();
                } else {
                    BaoLoi.setText("Tài khoản bị vô hiệu, vui lòng liên hệ quản lý");
                }
            } else {
                BaoLoi.setText("Sai Mật Khẩu");
            }
        }

// TODO add your handling code here:                // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void cbhienMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhienMKActionPerformed
        if (cbhienMK.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }       // TODO add your handling code here:
    }//GEN-LAST:event_cbhienMKActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void btnDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDangNhapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String name = txtDangNhap.getText();
            String pass = password.getText();
            LoadData.loadTableTaiKhoan();
            int index = -1;
            for (TaiKhoan tk : controller.arrayListTaiKhoan) {
                if (name.equals(tk.getMaNV().trim())) {
                    index = controller.arrayListTaiKhoan.indexOf(tk);
                }
            }
            if (index == -1) {
                BaoLoi.setText("Tài khoản Không Tồn Tại");
            } else {
                TaiKhoan tk = controller.arrayListTaiKhoan.get(index);
                if (tk.getMatKhau().equals(pass)) {
                    controller.tk = tk;

                    if (tk.getChucVu().getMaCV().equals("1") && tk.getTrangThaiXoa()== 0) {
                         Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
                        this.dispose();

                    } else if (tk.getChucVu().getMaCV().equals("2") && tk.getTrangThaiXoa() == 0) {
                         Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
                        this.dispose();
                    } else {
                        BaoLoi.setText("Tài khoản bị vô hiệu, vui lòng liên hệ quản lý");
                    }
                } else {
                    BaoLoi.setText("Sai Mật Khẩu");
                }
            }

        }               // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienDangNhap DN = new GiaoDienDangNhap();
                DN.setLocationRelativeTo(null);
                DN.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaoLoi;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cbhienMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtDangNhap;
    // End of variables declaration//GEN-END:variables
}
