/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;
import CONNECTION.DataConnection;
import CONNECTION.LoadData;
import Function.DigitsDocument;
import Model.KhuyenMai;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.CT_KhuyenMai;
import Model.DongHo;
import Model.NhanVien;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author Admin
 */
public class GiaoDienKhuyenMai extends javax.swing.JFrame {

    /**
     * Creates new form KhuyenMai
     */
    private DefaultTableModel myTable;
    private DefaultTableModel myTable1;
    private DefaultTableModel myTable2;

    public GiaoDienKhuyenMai() {
        initComponents();
        myTable = (DefaultTableModel) jTable1.getModel();
        myTable1 = (DefaultTableModel) jTable2.getModel();
        txtMaNV.setText(Controller.controller.tk.getMaNV());
        showData0();
        jTable1.setDefaultEditor(Object.class, null);;
        //jTable1.setSelectionBackground(Color.RED);
        jTable1.setSelectionMode(0);
        showData1();
        jTable2.setDefaultEditor(Object.class, null);;
        //jTable1.setSelectionBackground(Color.RED);
        jTable2.setSelectionMode(0);
        txtPTKM.setDocument(new DigitsDocument());
        txtMaNV.setEnabled(false);
    }

    private void showData0() {
        new LoadData();
        int dem = 0;
        myTable.setRowCount(0);
        for (KhuyenMai km : Controller.controller.arrayListKhuyenMai) {
            dem++;
            myTable.addRow(new Object[]{dem, km.getMaKM(), km.getMaNV(), km.getLyDoKM(), km.getNgayBD(), km.getNgayKT()});
        }
    }

    private void showData1() {
        new LoadData();
        int dem1 = 0;
        myTable1.setRowCount(0);
        for (CT_KhuyenMai ctkm : Controller.controller.arrayListCT_KhuyenMai) {
            dem1++;
            myTable1.addRow(new Object[]{dem1, ctkm.getMaKM(), ctkm.getMaDH(), ctkm.getPTKM()});
        }
    }

    private void showCTKM() {
        myTable2 = (DefaultTableModel) jTable2.getModel();
        new LoadData();
        int x = jTable1.getSelectedRow();
        int dem2 = 0;
        myTable2.setRowCount(0);
        String n = (String) myTable.getValueAt(x, 1);
        for (CT_KhuyenMai ctkm : Controller.controller.arrayListCT_KhuyenMai) {
            dem2++;
            if (ctkm.getMaKM().equals(n)) {
                myTable1.addRow(new Object[]{dem2, ctkm.getMaKM(), ctkm.getMaDH(), ctkm.getPTKM()});
            }
        }
    }
    private boolean check(String Ma){
    for(NhanVien nv : Controller.controller.arrayListNhanVien){
        if((nv.getMaNV().trim().equals(Ma.trim()))){
        return true;
        
        }
        
    
    }
    return false;
    }
    private boolean check1(String Ma){
    for(KhuyenMai km : Controller.controller.arrayListKhuyenMai){
        if((km.getMaKM().trim().equals(Ma.trim()))){
        return true;
        
        }
        
    
    }
    return false;
    }
    private boolean check2(String Ma){
    for(DongHo dh : Controller.controller.arrayListDongHo){
        if((dh.getMaDH().trim().equals(Ma.trim()))){
        return true;
        
        }
        
    
    }
    return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Home = new javax.swing.JButton();
        KM = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLyDo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dateNgayKT = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        baoloi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TuNgay = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        DenNgay = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPTKM = new javax.swing.JTextField();
        CTKM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtCTKM = new javax.swing.JTextField();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        baoloi1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KHUYẾN MÃI");
        setResizable(false);

        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        KM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBackground(new java.awt.Color(247, 220, 104));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KM", "Mã NV", "Lí do", "Ngày BD", "Ngày KT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã KM:");

        txtMaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã NV:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Lí do:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ngày BD:");

        dateNgayBD.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngày KT:");

        dateNgayKT.setDateFormatString("yyyy-MM-dd");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa ");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        baoloi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi.setForeground(new java.awt.Color(244, 108, 63));
        baoloi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baoloi.setText("Thông báo:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 149, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHUYẾN MÃI");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Từ ngày:");

        TuNgay.setDateFormatString("yyyy-MM-dd");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Đến ngày:");

        DenNgay.setDateFormatString("yyyy-MM-dd");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        jButton3.setText("Tra cứu");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        jButton5.setText("KM còn hạn");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        jButton4.setText("KM hết hạn");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mã DH:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("PTKM:");

        txtPTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KMLayout = new javax.swing.GroupLayout(KM);
        KM.setLayout(KMLayout);
        KMLayout.setHorizontalGroup(
            KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KMLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KMLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KMLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtMaNV)
                            .addComponent(txtLyDo)
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dateNgayKT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(dateNgayBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaDH)
                                    .addComponent(txtPTKM)))))
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        KMLayout.setVerticalGroup(
            KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KMLayout.createSequentialGroup()
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KMLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KMLayout.createSequentialGroup()
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtPTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(KMLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(KMLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(KMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jButton3.getAccessibleContext().setAccessibleName("");
        jButton5.getAccessibleContext().setAccessibleName("");
        jButton4.getAccessibleContext().setAccessibleName("");

        CTKM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 149, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT KHUYẾN MÃI");

        jTable2.setBackground(new java.awt.Color(247, 220, 104));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã KM", "Mã DH", "PTKM (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã KM:");

        txtCTKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTKMActionPerformed(evt);
            }
        });

        btnXoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa1.setText("Xóa ");
        btnXoa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnreset1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnreset1.setText("Reset");
        btnreset1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        baoloi1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi1.setForeground(new java.awt.Color(244, 108, 63));
        baoloi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CTKMLayout = new javax.swing.GroupLayout(CTKM);
        CTKM.setLayout(CTKMLayout);
        CTKMLayout.setHorizontalGroup(
            CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKMLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baoloi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CTKMLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CTKMLayout.createSequentialGroup()
                                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CTKMLayout.setVerticalGroup(
            CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKMLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTKMLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(CTKMLayout.createSequentialGroup()
                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(CTKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(baoloi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btn_Home))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(CTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKMActionPerformed

    private void txtCTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTKMActionPerformed

    private void txtPTKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTKMActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if ( txtMaNV.getText().equals("") || txtLyDo.getText().equals("") || dateNgayBD.getDate().equals("") || dateNgayKT.getDate().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin khuyến mãi!");
        } else {

            int row = jTable1.getSelectedRow();
            int PTKM = Integer.parseInt(txtPTKM.getText());
            KhuyenMai km = new KhuyenMai(txtMaKM.getText(), txtMaNV.getText(), txtLyDo.getText(), dateNgayBD.getDate(), dateNgayKT.getDate());
            CT_KhuyenMai ctkm = new CT_KhuyenMai(txtMaKM.getText(), txtMaDH.getText(), PTKM);
            if (jTable1.getSelectedRow() == -1) {

                for (KhuyenMai kmm : Controller.controller.arrayListKhuyenMai) {
                    if (kmm.getMaKM().equals(txtMaKM.getText())) {
                        baoloi.setText("Mã khuyến mãi đã tồn tại!");
                        return;
                    }
                }
                if(!check(txtMaNV.getText())){
                    baoloi.setText("Mã nhân viên không hợp lệ");
                return;
                }else
                CONNECTION.InsertData.insertKhuyenMai(km,ctkm);
                showData0();
                showData1();
                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);
            } else {

                CONNECTION.UpdateData.updateKhuyenMai(km);

            }
            showData0();
            //showData();
            jTable1.getSelectionModel().setSelectionInterval(row, row);
        }
        String x = "";
        txtMaKM.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        txtLyDo.setText(x);
        jTable1.setModel(myTable);
        showData0();

// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn khuyến mãi");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Khuyến Mãi?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                CONNECTION.DeleteData.deleteKhuyenMai((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                showData0();
            }
        }
        String x = "";
        txtMaKM.setText(x);
        txtLyDo.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        if (jTable2.getSelectedRow() == -1) {
            baoloi1.setText("Vui lòng chọn chi tiết khuyến mãi");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Chi Tiết Khuyến Mãi?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                CONNECTION.DeleteData.delelteCT_KhuyenMai((String) jTable2.getValueAt(jTable2.getSelectedRow(), 1), (String) jTable2.getValueAt(jTable2.getSelectedRow(), 2));
                showData1();
            }
        }
        String x = "";
        txtCTKM.setText(x);
        txtMaDH.setText(x);
        txtPTKM.setText(x);
        txtCTKM.setEnabled(true);
        txtMaDH.setEnabled(true);
        showData1();
// TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        btnThem.setEnabled(false);
        txtMaKM.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtMaKM.setText((String) jTable1.getValueAt(row, 1));
        txtMaNV.setText((String) jTable1.getValueAt(row, 2));
        txtLyDo.setText((String) jTable1.getValueAt(row, 3));
        String datebd = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String datekt = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        datebd = datebd.substring(8, 10) + "/" + datebd.substring(5, 7) + "/" + datebd.substring(0, 4);
        datekt = datekt.substring(8, 10) + "/" + datekt.substring(5, 7) + "/" + datekt.substring(0, 4);

        try {
            java.util.Date datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(datebd);
            dateNgayBD.setDate(datetmp);
            java.util.Date datetmp1 = new SimpleDateFormat("dd/MM/yyyy").parse(datekt);
            dateNgayKT.setDate(datetmp1);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getClickCount() == 2) {
            jTable2.setDefaultEditor(Object.class, null);
            //jTable1.setSelectionBackground(Color.RED);
            jTable2.setSelectionMode(0);
            showCTKM();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        txtCTKM.setEnabled(false);
        txtMaDH.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        txtCTKM.setText((String) jTable2.getValueAt(row, 1));
        txtMaDH.setText((String) jTable2.getValueAt(row, 2));
        txtPTKM.setText(jTable2.getValueAt(row, 3).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaKM.getText().equals("") || txtMaNV.getText().equals("") || txtLyDo.getText().equals("") || dateNgayBD.getDate().equals(null) || dateNgayKT.getDate().equals(null)) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin khuyến mãi!");
        } else {

            int row = jTable1.getSelectedRow();
           
            KhuyenMai km = new KhuyenMai(txtMaKM.getText(), txtMaNV.getText(), txtLyDo.getText(), dateNgayBD.getDate(), dateNgayKT.getDate());

                if(!check(txtMaNV.getText())){
                    baoloi.setText("Mã nhân viên không hợp lệ");
                return;
                }else
                CONNECTION.UpdateData.updateKhuyenMai(km);

            
            showData0();
            //showData();
            jTable1.getSelectionModel().setSelectionInterval(row, row);
        }
        String x = "";
        txtMaKM.setText(x);
        txtLyDo.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        showData0();
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (txtCTKM.getText().equals("") || txtMaDH.getText().equals("") || txtPTKM.getText().equals("")) {
            baoloi1.setText("Vui lòng nhập đầy đủ thông tin chi tiết khuyến mãi!");
        } else {

            int row = jTable2.getSelectedRow();
            int PTKM = Integer.parseInt(txtPTKM.getText());
         
            CT_KhuyenMai ctkm = new CT_KhuyenMai(txtCTKM.getText(), txtMaDH.getText(), PTKM);
            String madh = (String) jTable2.getValueAt(row, 2);
            String makm = (String) jTable2.getValueAt(row, 1);

            
            for (CT_KhuyenMai ctkmm : Controller.controller.arrayListCT_KhuyenMai) {
                if (PTKM > 100) {
                    baoloi1.setText("Phần trăm khuyến mãi <= 100");
                } else {
                    String x = "";
                    txtCTKM.setText(x);
                    txtMaDH.setText(x);
                    txtPTKM.setText(x);
                    txtCTKM.setEnabled(true);
                    txtMaDH.setEnabled(true);
                    
                    CONNECTION.UpdateData.updateCT_KhuyenMai(ctkm);

                    break;
                }
            }
            jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount() - 1, jTable2.getRowCount() - 1);
            showData1();

            //showData1();
            // jTable2.getSelectionModel().setSelectionInterval(row, row);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
       Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        String x = "";
        txtMaKM.setText(x);
        dateNgayBD.setDate(null);
        dateNgayKT.setDate(null);
        txtMaKM.setEnabled(true);
        btnThem.setEnabled(true);
        txtLyDo.setText(x);
        jTable1.setModel(myTable);
        TuNgay.setDate(null);
        DenNgay.setDate(null);
        showData0();
// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        String x = "";
        txtCTKM.setText(x);
        txtMaDH.setText(x);
        txtPTKM.setText(x);
        txtCTKM.setEnabled(true);
        showData1();
        txtMaDH.setEnabled(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnreset1ActionPerformed
public void showTheoNgayBD(String d1, String d2){
     DataConnection.createStatement();
         try {
            String sql = ("select * from dbo.KhuyenMai where NgayBD between ? and ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1,d1);
            ps.setString(2, d2);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while(rs.next()){
            row = new Object[6];
            row[0] = dem++;
            row[1] = rs.getString("MaKM");
            row[2] = rs.getString("MaNV");
            row[3] = rs.getDate("LyDo");
            row[4] = rs.getDate("NgayBD");
            row[5] = rs.getDate("NgayKT");
            mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jTable1.setModel(new DefaultTableModel(null,new Object[]{"STT","Mã khuyến mãi","Mã NV","Lý do","Ngày bắt đầu","Ngày kết thúc"}));
        try{
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String jdate = date.format(TuNgay.getDate());
            String jdate1 = date.format(DenNgay.getDate());
            showTheoNgayBD(jdate,jdate1);

        } catch (Exception ex) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
public void showConKM(String d1){
     DataConnection.createStatement();
         try {
            String sql = ("select * from dbo.KhuyenMai where NgayKT > ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1,d1);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while(rs.next()){
            row = new Object[6];
            row[0] = dem++;
            row[1] = rs.getString("MaKM");
            row[2] = rs.getString("MaNV");
            row[3] = rs.getString("LyDo");
            row[4] = rs.getDate("NgayBD");
            row[5] = rs.getDate("NgayKT");
            mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         long millis=System.currentTimeMillis();
            java.sql.Date date=new java.sql.Date(millis);
            String time = date.toString();
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"STT","Mã khuyến mãi","Mã NV","Lý do","Ngày bắt đầu","Ngày kết thúc"}));
        try{
           
            showConKM(time);

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed
public void showHetKM(String d1){
     DataConnection.createStatement();
         try {
            String sql = ("select * from dbo.KhuyenMai where NgayKT < ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1,d1);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while(rs.next()){
            row = new Object[6];
            row[0] = dem++;
            row[1] = rs.getString("MaKM");
            row[2] = rs.getString("MaNV");
            row[3] = rs.getString("LyDo");
            row[4] = rs.getDate("NgayBD");
            row[5] = rs.getDate("NgayKT");
            mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            long millis=System.currentTimeMillis();
            java.sql.Date date=new java.sql.Date(millis);
            String time = date.toString();
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"STT","Mã khuyến mãi","Mã NV","Lý do","Ngày bắt đầu","Ngày kết thúc"}));
        try{
           
            showHetKM(time);

        } catch (Exception ex) {

        }
              
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienKhuyenMai KM = new GiaoDienKhuyenMai();
                KM.setLocationRelativeTo(null);
                KM.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CTKM;
    private com.toedter.calendar.JDateChooser DenNgay;
    private javax.swing.JPanel KM;
    private com.toedter.calendar.JDateChooser TuNgay;
    private javax.swing.JLabel baoloi;
    private javax.swing.JLabel baoloi1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private com.toedter.calendar.JDateChooser dateNgayBD;
    private com.toedter.calendar.JDateChooser dateNgayKT;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCTKM;
    private javax.swing.JTextField txtLyDo;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtPTKM;
    // End of variables declaration//GEN-END:variables
}
