/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;

import CONNECTION.LoadData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.NhanVien;
import Model.TaiKhoan;
import Function.DigitsDocument;
import Model.ChucVu;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class GiaoDienNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien
     */
    private DefaultTableModel myTable;
    private DefaultTableModel model;
    private Map<String, Integer> comboBoxItems; // Thuộc tính để lưu trữ comboBoxItems
    private String selectedImageUrl;

    public GiaoDienNhanVien() {
        initComponents();
        myTable = (DefaultTableModel) tbl_nv.getModel();
        cbbGT.setSelectedItem(null);
        cbbTrangThai.setSelectedItem(null);
        showData();
        comboBoxItems = new HashMap<>(); // Khởi tạo comboBoxItems
        comboBoxItems.put("Làm việc", 0);
        comboBoxItems.put("Nghỉ làm", 1);

        for (String item : comboBoxItems.keySet()) {
            cbbTrangThai.addItem(item);
        }
        tbl_nv.setDefaultEditor(Object.class, null);;
        //jTable1.setSelectionBackground(Color.RED);
        tbl_nv.setSelectionMode(0);
        txtSDT.setDocument(new DigitsDocument());
        btnXemTK.setEnabled(false);
        if (Controller.controller.tk.getChucVu().getMaCV().equals("1")) {

        } else {
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            btnreset.setEnabled(false);
            TxtTen.setEnabled(false);
            txtDC.setEnabled(false);
            txtHoNV.setEnabled(false);
            txtMaNV.setEnabled(false);
            txtNS.setEnabled(false);
            txtSDT.setEnabled(false);
            cbbGT.setEnabled(false);
            cbbTrangThai.setEnabled(false);

        }
        txtMaNV.setEnabled(false);

    }

    private void showData() {
        new LoadData();
        myTable.setRowCount(0);
        int dem = 0;
        for (NhanVien nv : Controller.controller.arrayListNhanVien) {
            dem++;
            myTable.addRow(new Object[]{dem, nv.getMaNV(), nv.getHoNV(), nv.getTenNV(), nv.getGtNV(), nv.getNsNV(), nv.getDcNV(), nv.getStdNV(), nv.getTrangThai(), new ImageIcon(nv.getHinhAnh())});

        }
    }

    private void TimKiem(String Str) {
        model = (DefaultTableModel) tbl_nv.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tbl_nv.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(Str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtxTK = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cttt_nv = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtDC = new javax.swing.JTextField();
        txtHoNV = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbGT = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        txtNS = new com.toedter.calendar.JDateChooser();
        btnXemTK = new javax.swing.JButton();
        btnHA = new javax.swing.JButton();
        lableAnh = new javax.swing.JLabel();
        pnl_tbl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nv = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        baoloi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DANH SÁCH NHÂN VIÊN");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 149, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(51, 51, 51));

        txtxTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxTKActionPerformed(evt);
            }
        });
        txtxTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtxTKKeyReleased(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/funnel-icon.png"))); // NOI18N
        jButton14.setText("Lọc");
        jButton14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Bộ lọc thông tin");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Vui lòng nhập thông tin cần lọc vào ô trống");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(71, 71, 71))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtxTK, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(14, 14, 14))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel25)
                .addGap(10, 10, 10))
        );

        cttt_nv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ngày sinh:");

        txtDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDCActionPerformed(evt);
            }
        });

        txtHoNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoNVActionPerformed(evt);
            }
        });

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã nhân viên:");

        TxtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Họ:");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Giới tính:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tên: ");

        cbbGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Chi tiết thông tin");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Trạng thái");

        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        txtNS.setDateFormatString("yyyy-MM-dd");

        btnXemTK.setText("Xem tài khoản");
        btnXemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTKActionPerformed(evt);
            }
        });

        btnHA.setText("Hình ảnh:");
        btnHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAActionPerformed(evt);
            }
        });

        lableAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout cttt_nvLayout = new javax.swing.GroupLayout(cttt_nv);
        cttt_nv.setLayout(cttt_nvLayout);
        cttt_nvLayout.setHorizontalGroup(
            cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cttt_nvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(145, 749, Short.MAX_VALUE))
            .addGroup(cttt_nvLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cttt_nvLayout.createSequentialGroup()
                        .addComponent(btnHA)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cttt_nvLayout.createSequentialGroup()
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(cttt_nvLayout.createSequentialGroup()
                                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(36, 36, 36)
                                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lableAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cttt_nvLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(txtHoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cttt_nvLayout.createSequentialGroup()
                                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtDC, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(cttt_nvLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        cttt_nvLayout.setVerticalGroup(
            cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cttt_nvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cttt_nvLayout.createSequentialGroup()
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(btnXemTK)))
                    .addGroup(cttt_nvLayout.createSequentialGroup()
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cttt_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHA)
                    .addComponent(lableAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnl_tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_tbl.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Danh sách nhân viên");

        tbl_nv.setBackground(new java.awt.Color(247, 220, 104));
        tbl_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NV", "Họ ", "Tên", "Giới tính", "Ngày sinh", "Địa chỉ", "SDT", "Trạng Thái", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_nvMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_nvMouseReleased(evt);
            }
        });
        tbl_nv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_nvKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nv);
        if (tbl_nv.getColumnModel().getColumnCount() > 0) {
            tbl_nv.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_nv.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        baoloi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi.setForeground(new java.awt.Color(244, 108, 63));
        baoloi.setText("Thông báo:");
        baoloi.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout pnl_tblLayout = new javax.swing.GroupLayout(pnl_tbl);
        pnl_tbl.setLayout(pnl_tblLayout);
        pnl_tblLayout.setHorizontalGroup(
            pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tblLayout.createSequentialGroup()
                .addGroup(pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tblLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(pnl_tblLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnl_tblLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10))
        );
        pnl_tblLayout.setVerticalGroup(
            pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tblLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_tbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cttt_nv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cttt_nv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_tbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTenActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDCActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        // TODO add your handling code here:
        if (txtSDT.getText().length() != 10) {
            baoloi.setText("thông tin về số điện thoại không hợp lệ!");
            return;
        } else {
            for (int i = 0; i < txtSDT.getText().length(); i++) {
                if (Character.isDigit(txtSDT.getText().charAt(i))) {
                    continue;
                } else {
                    baoloi.setText("thông tin về số điện thoại không hợp lệ!");
                    return;
                }

            }
        }

        if (TxtTen.getText().equals("") || txtDC.getText().equals("") || txtHoNV.getText().equals("") || txtNS.getDate().equals("") || txtSDT.getText().equals("") || cbbTrangThai.getSelectedItem().equals(null)) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin nhân viên!");
        } else {
            int row = tbl_nv.getSelectedRow();
            String GT = (String) cbbGT.getSelectedItem();
            String selectedItem = (String) cbbTrangThai.getSelectedItem();
            int TT = comboBoxItems.get(selectedItem);
            String HinhAnh = selectedImageUrl;
            NhanVien nv = new NhanVien(txtMaNV.getText(), txtHoNV.getText(), TxtTen.getText(), GT, txtDC.getText(), txtSDT.getText(), TT, txtNS.getDate(), HinhAnh);
            ChucVu cv = null;

            if (tbl_nv.getSelectedRow() == -1) {

                for (NhanVien nvv : Controller.controller.arrayListNhanVien) {
                    if (nvv.getMaNV().equals(txtMaNV.getText())) {
                        baoloi.setText("Nhân viên đã tồn tại!");
                        return;
                    }
                }
                for (TaiKhoan tkk : Controller.controller.arrayListTaiKhoan) {
                    if (txtMaNV.getText().equals(tkk.getMaNV())) {
                        baoloi.setText("Tên đăng nhập đã tồn tại!");
                        return;
                    }
                }

                CONNECTION.InsertData.insertNhanVien(nv);
                showData();

                tbl_nv.getSelectionModel().setSelectionInterval(tbl_nv.getRowCount() - 1, tbl_nv.getRowCount() - 1);

            } else {

                CONNECTION.UpdateData.updateNhanVien(nv);
                TaiKhoan tk = new TaiKhoan(nv.getMaNV(), txtSDT.getText(), 0, cv, "1");

                CONNECTION.UpdateData.upadateTaiKhoan(tk);

            }
            showData();
            tbl_nv.getSelectionModel().setSelectionInterval(row, row);

        }
        String x = "";
        TxtTen.setText(x);
        txtDC.setText(x);
        cbbGT.setSelectedItem(null);
        txtHoNV.setText(x);
        txtMaNV.setText(x);
        txtNS.setDate(null);
        txtSDT.setText(x);
        btnThem.setEnabled(true);
        cbbTrangThai.setSelectedItem(null);
        lableAnh.setIcon(null);

        showData();
// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtHoNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoNVActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (tbl_nv.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn nhân viên");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Nhân Viên?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(tbl_nv.getValueAt(tbl_nv.getSelectedRow(), 1));
                CONNECTION.DeleteData.deletetNhanVien((String) tbl_nv.getValueAt(tbl_nv.getSelectedRow(), 1));
                CONNECTION.DeleteData.deleteTaiKhoan((String) tbl_nv.getValueAt(tbl_nv.getSelectedRow(), 1));
                showData();
            }
        }
        String x = "";
        TxtTen.setText(x);
        txtDC.setText(x);
        cbbGT.setSelectedItem(null);
        txtHoNV.setText(x);
        txtMaNV.setText(x);
        txtNS.setDate(null);
        txtSDT.setText(x);
        btnThem.setEnabled(true);
        cbbTrangThai.setSelectedItem(null);
        lableAnh.setIcon(null);

        showData();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed

        String x = "";
        TxtTen.setText(x);
        txtDC.setText(x);
        cbbGT.setSelectedItem(null);
        txtHoNV.setText(x);
        txtMaNV.setText(x);
        txtNS.setDate(null);
        txtSDT.setText(x);
        btnThem.setEnabled(true);
        cbbTrangThai.setSelectedItem(null);
        lableAnh.setIcon(null);
        showData();
// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        // TODO add your handling code here:
        if (txtSDT.getText().length() != 10) {
            baoloi.setText("thông tin về số điện thoại không hợp lệ!");
            return;
        } else {
            for (int i = 0; i < txtSDT.getText().length(); i++) {
                if (Character.isDigit(txtSDT.getText().charAt(i))) {
                    continue;
                } else {
                    baoloi.setText("thông tin về số điện thoại không hợp lệ!");
                    return;
                }

            }
        }

        if (TxtTen.getText().equals("") || txtDC.getText().equals("") || txtHoNV.getText().equals("") || txtMaNV.getText().equals("") || txtNS.getDate().equals("") || txtSDT.getText().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin nhân viên!");
        } else {

            int row = tbl_nv.getSelectedRow();
            String SDT = (String) myTable.getValueAt(row, 7);
            String GT = (String) cbbGT.getSelectedItem();
            String selectedItem = (String) cbbTrangThai.getSelectedItem();
            int TT = comboBoxItems.get(selectedItem);
            String HinhAnh = selectedImageUrl;
            NhanVien nvv = new NhanVien(txtMaNV.getText(), txtHoNV.getText(), TxtTen.getText(), GT, txtDC.getText(), SDT, TT, txtNS.getDate(), HinhAnh);

            for (NhanVien nv : Controller.controller.arrayListNhanVien) {

                if ((txtSDT.getText().equals(nv.getStdNV())) && (!txtSDT.getText().equals(SDT))) {
                    baoloi.setText("Số điện thoại bị trùng");
                    return;

                }
            }
            CONNECTION.UpdateData.updateNhanVien(nvv);
            tbl_nv.getSelectionModel().setSelectionInterval(row, row);

        }

        String x = "";
        TxtTen.setText(x);
        txtDC.setText(x);
        cbbGT.setSelectedItem(null);
        txtHoNV.setText(x);
        txtMaNV.setText(x);
        txtNS.setDate(null);
        txtSDT.setText(x);
        btnThem.setEnabled(true);
        cbbTrangThai.setSelectedItem(null);
        lableAnh.setIcon(null);

        showData();
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Home home = new Home();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tbl_nvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_nvKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_nvKeyReleased

    private void tbl_nvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMousePressed
        txtMaNV.setEnabled(false);
        btnThem.setEnabled(false);
        btnXemTK.setEnabled(true);
        baoloi.setText("");// TODO add your handling code here:
        int row = tbl_nv.getSelectedRow();
        txtMaNV.setText((String) tbl_nv.getValueAt(row, 1));
        txtHoNV.setText((String) tbl_nv.getValueAt(row, 2));
        TxtTen.setText((String) tbl_nv.getValueAt(row, 3));
        cbbGT.setSelectedItem((String) tbl_nv.getValueAt(row, 4));
        String dateNS = tbl_nv.getValueAt(tbl_nv.getSelectedRow(), 5).toString();
        txtDC.setText((String) tbl_nv.getValueAt(row, 6));
        txtSDT.setText((String) tbl_nv.getValueAt(row, 7));
        // cbbTrangThai.setSelectedItem((String) tbl_nv.getValueAt(row, 8));

        Object value = tbl_nv.getValueAt(row, 8);
        if (value != null) {
            int selectedValue = Integer.parseInt(value.toString());
            for (Map.Entry<String, Integer> entry : comboBoxItems.entrySet()) {
                if (entry.getValue() == selectedValue) {
                    cbbTrangThai.setSelectedItem(entry.getKey());
                    break;
                }
            }
        }

        dateNS = dateNS.substring(8, 10) + "/" + dateNS.substring(5, 7) + "/" + dateNS.substring(0, 4);

        try {
            java.util.Date datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(dateNS);
            txtNS.setDate(datetmp);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        selectedImageUrl = tbl_nv.getValueAt(row, 9).toString();
        ImageIcon imageIcon = new ImageIcon(tbl_nv.getValueAt(row, 9).toString());
        Image image = imageIcon.getImage().getScaledInstance(lableAnh.getWidth(), lableAnh.getHeight(), Image.SCALE_SMOOTH);
        lableAnh.setIcon(new ImageIcon(image));

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_nvMousePressed

    private void txtxTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxTKActionPerformed

    private void txtxTKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxTKKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtxTKKeyReleased

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String kh = txtxTK.getText();
        TimKiem(kh);// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void cbbGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGTActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void tbl_nvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_nvMouseReleased

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        String number = txtSDT.getText();
        int length = number.length();

        if (length < 10) {
            txtSDT.setEditable(true);
        } else {
            txtSDT.setEditable(false);

            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtSDT.setEditable(true);
            } else {
                txtSDT.setEditable(false);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTKeyPressed

    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    private void btnXemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTKActionPerformed
        TaiKhoanNhanVien TaiKhoanNhanVien = new TaiKhoanNhanVien(txtMaNV.getText());
        TaiKhoanNhanVien.setLocationRelativeTo(null);
        TaiKhoanNhanVien.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemTKActionPerformed

    private void btnHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("E:\\LTHDT\\BanDongHo\\BanDongHoOnline\\src"));
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            // Hiển thị ảnh đã chọn
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image image = imageIcon.getImage().getScaledInstance(lableAnh.getWidth(), lableAnh.getHeight(), Image.SCALE_SMOOTH);
            lableAnh.setIcon(new ImageIcon(image));
            System.err.print(lableAnh.getIcon());
            selectedImageUrl = selectedFile.getAbsolutePath();
        }
    }//GEN-LAST:event_btnHAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienNhanVien NV = new GiaoDienNhanVien();
                NV.setLocationRelativeTo(null);
                NV.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTen;
    private javax.swing.JLabel baoloi;
    private javax.swing.JButton btnHA;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXemTK;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> cbbGT;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JPanel cttt_nv;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableAnh;
    private javax.swing.JPanel pnl_tbl;
    private javax.swing.JTable tbl_nv;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtHoNV;
    private javax.swing.JTextField txtMaNV;
    private com.toedter.calendar.JDateChooser txtNS;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtxTK;
    // End of variables declaration//GEN-END:variables
}
