/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;

import java.sql.PreparedStatement;
import CONNECTION.DataConnection;
import CONNECTION.LoadData;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.CT_PhieuBaoHanh;
import Model.DongHo;
import Model.NhanVien;
import Model.PhieuBaoHanh;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author Admin
 */
public class GiaoDienBaoHanh extends javax.swing.JFrame {

    /**
     * Creates new form BaoHanh
     */
    private DefaultTableModel myTable;
    private DefaultTableModel myTable1;
    private DefaultTableModel myTable2;

    public GiaoDienBaoHanh() {

        initComponents();
        myTable = (DefaultTableModel) jTable1.getModel();
        myTable1 = (DefaultTableModel) jTable2.getModel();
        myTable2 = (DefaultTableModel) jTable2.getModel();
        txtMNV.setEnabled(false);
        txtMNV.setText(Controller.controller.tk.getMaNV());
        showData();
        showData1();
        jTable1.setSelectionMode(0);
        txtPBH.setEnabled(false);
    }

    private void showData() {
        new LoadData();
        int dem = 0;
        myTable.setRowCount(0);
        for (PhieuBaoHanh bh : Controller.controller.arrayListPhieuBaoHanh) {
            dem++;
            myTable.addRow(new Object[]{dem, bh.getMaPBH(), bh.getMaDH(), bh.getNgayBD(), bh.getNgayKT()});
        }

    }

    private void showData1() {
        new LoadData();
        int dem1 = 0;

        myTable1.setRowCount(0);
        for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh) {
            dem1++;
            myTable1.addRow(new Object[]{dem1, ctbh.getMaPBH(), ctbh.getMaNV(), ctbh.getTrangThai()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Home = new javax.swing.JButton();
        pnl_BH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtPBH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMDH = new javax.swing.JTextField();
        Tim = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        baoloi = new javax.swing.JLabel();
        dateBD = new com.toedter.calendar.JDateChooser();
        dateKT = new com.toedter.calendar.JDateChooser();
        DenNgay = new com.toedter.calendar.JDateChooser();
        TuNgay = new com.toedter.calendar.JDateChooser();
        pnl_CTBH = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCTBH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTT = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtMNV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BẢO HÀNH");
        setResizable(false);

        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        btn_Home.setToolTipText("");
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        pnl_BH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBackground(new java.awt.Color(247, 220, 104));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu bảo hành", "Mã đồng hồ", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã phiếu bảo hành:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mã đồng hồ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ngày bắt đầu:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày kết thúc:");

        btnThem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem1.setText("Thêm ");
        btnThem1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa1.setText("Xóa ");
        btnXoa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 149, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU BẢO HÀNH");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        Tim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        Tim.setText("Tra cứu");
        Tim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Từ ngày");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Đến ngày");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/no ok.png"))); // NOI18N
        jButton4.setText("PBH hết hạn");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ok-icon.png"))); // NOI18N
        jButton5.setText("PBH còn hạn");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        baoloi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        baoloi.setForeground(new java.awt.Color(244, 108, 63));
        baoloi.setText("Thông báo: ");

        javax.swing.GroupLayout pnl_BHLayout = new javax.swing.GroupLayout(pnl_BH);
        pnl_BH.setLayout(pnl_BHLayout);
        pnl_BHLayout.setHorizontalGroup(
            pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_BHLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_BHLayout.createSequentialGroup()
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_BHLayout.createSequentialGroup()
                                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMDH, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(txtPBH, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(dateBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_BHLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_BHLayout.createSequentialGroup()
                                                .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                                .addGap(214, 214, 214)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnl_BHLayout.createSequentialGroup()
                                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                        .addComponent(Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)))))
                .addGap(12, 12, 12))
        );
        pnl_BHLayout.setVerticalGroup(
            pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BHLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_BHLayout.createSequentialGroup()
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dateBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                .addComponent(Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(pnl_BHLayout.createSequentialGroup()
                                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_BHLayout.createSequentialGroup()
                                        .addComponent(TuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(DenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl_BHLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel8)))
                                .addGap(2, 2, 2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_BHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pnl_CTBH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 149, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT PHIẾU BẢO HÀNH");

        jTable2.setBackground(new java.awt.Color(247, 220, 104));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu bảo hành", "Trạng thái", "Mã nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mã phiếu bảo hành:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Trạng Thái:");

        txtTT.setColumns(20);
        txtTT.setRows(5);
        jScrollPane3.setViewportView(txtTT);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mã nhân viên:");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.setAutoscrolls(true);
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa ");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_CTBHLayout = new javax.swing.GroupLayout(pnl_CTBH);
        pnl_CTBH.setLayout(pnl_CTBHLayout);
        pnl_CTBHLayout.setHorizontalGroup(
            pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CTBHLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CTBHLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCTBH))
                    .addGroup(pnl_CTBHLayout.createSequentialGroup()
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(51, 51, 51)
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(txtMNV)))
                    .addGroup(pnl_CTBHLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        pnl_CTBHLayout.setVerticalGroup(
            pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CTBHLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_CTBHLayout.createSequentialGroup()
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCTBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(pnl_CTBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Home)
                    .addComponent(pnl_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_CTBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(pnl_CTBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void LayCT() {
        myTable2 = (DefaultTableModel) jTable2.getModel();
        new LoadData();
        int dem2 = 0;
        int x = jTable1.getSelectedRow();
        myTable2.setRowCount(0);
        String n = (String) myTable.getValueAt(x, 1);
        for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh) {
            dem2++;
            if (ctbh.getMaPBH().equals(n)) {
                jTable2.removeAll();
                myTable2.addRow(new Object[]{dem2, ctbh.getMaPBH(), ctbh.getMaNV(), ctbh.getTrangThai()});
            }

        }
    }

    private boolean check(String Ma) {
        for (PhieuBaoHanh bh : Controller.controller.arrayListPhieuBaoHanh) {
            if ((bh.getMaPBH().trim().equals(Ma.trim()))) {
                return true;

            }

        }
        return false;
    }

    private boolean check1(String Ma) {
        for (NhanVien nv : Controller.controller.arrayListNhanVien) {
            if (nv.getMaNV().trim().equals(Ma.trim())) {
                return true;
            }

        }
        return false;
    }

    private boolean check2(String Ma) {
        for (DongHo dh : Controller.controller.arrayListDongHo) {
            if (dh.getMaDH().trim().equals(Ma.trim())) {
                return true;
            }

        }
        return false;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (txtCTBH.getText().equals("") || txtTT.getText().equals("") || txtMNV.getText().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin chi tiết phiếu bảo hành!");
        } else {

            int row = jTable2.getSelectedRow();

            CT_PhieuBaoHanh ctph = new CT_PhieuBaoHanh(txtCTBH.getText(), txtTT.getText(), txtMNV.getText());
            if (jTable2.getSelectedRow() == -1) {

                for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh) {
                    if (ctbh.getMaPBH().equals(txtCTBH.getText())) {
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                }

                if (!check(txtCTBH.getText())) {
                    baoloi.setText("Mã bảo hành không hợp lệ");
                    return;
                } else if (!check1(txtMNV.getText())) {
                    baoloi.setText("Mã nhân viên không hợp lệ");
                    return;
                } else {
                    CONNECTION.InsertData.insertCT_BaoHanh(ctph);
                }

                showData1();

                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount() - 1, jTable2.getRowCount() - 1);

            } else {

                CONNECTION.UpdateData.updateCT_PhieuBaoHanh(ctph);

            }
            showData1();

        }
        String y = "";
        txtCTBH.setText(y);
        txtMNV.setText(y);
        txtTT.setText(y);
        txtCTBH.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed

        if ( txtMDH.getText().equals("") || dateBD.getDate().equals("") || dateKT.getDate().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin phiếu bảo hành!");
        } else {

            int row = jTable1.getSelectedRow();

            PhieuBaoHanh bh = new PhieuBaoHanh(txtPBH.getText(), txtMDH.getText(), dateBD.getDate(), dateKT.getDate());
            if (jTable1.getSelectedRow() == -1) {

                for (PhieuBaoHanh bhh : Controller.controller.arrayListPhieuBaoHanh) {
                    if (bhh.getMaPBH().equals(txtPBH.getText())) {
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                }
                if (!check2(txtMDH.getText())) {
                    baoloi.setText("Mã đồng hồ không hợp lệ");
                    return;
                } else {
                    CONNECTION.InsertData.insertPhieuBaoHanh(bh);
                }
                showData();

                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);

            } else {

                CONNECTION.UpdateData.updatePhieuBaoHanh(bh);

            }

            jTable1.getSelectionModel().setSelectionInterval(row, row);
        }
        String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        dateBD.setDate(null);
        dateKT.setDate(null);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        jTable1.setModel(myTable);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        jTable1.setModel(myTable);
        dateBD.setDate(null);
        dateKT.setDate(null);
        btnThem1.setEnabled(true);
        jTable1.setModel(myTable);
        TuNgay.setDate(null);
        DenNgay.setDate(null);
        showData();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String y = "";
        txtCTBH.setText(y);
        txtMNV.setText(y);
        txtTT.setText(y);
        txtCTBH.setEnabled(true);
        jTable2.setModel(myTable1);
        btnThem.setEnabled(true);
        showData1();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed

        Xoa();
        String x = "";
        txtPBH.setText(x);
        txtMDH.setText(x);
        dateBD.setDate(null);
        dateKT.setDate(null);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
        btnThem1.setEnabled(true);
        jTable1.setModel(myTable);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed
    private void Xoa() {
        if (jTable1.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn phiếu bảo hành");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Phiếu Bảo Hành?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                CONNECTION.DeleteData.deleteBaoHanh((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                showData();
                showData1();
            }
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (jTable2.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn chi tiết bảo hành");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Chi Tiết Bảo Hành?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                CONNECTION.DeleteData.deleteCT_PhieuBaoHanh((String) jTable2.getValueAt(jTable2.getSelectedRow(), 1));
                showData1();
            }
        }
        String y = "";
        txtCTBH.setText(y);
        txtMNV.setText(y);
        txtTT.setText(y);
        txtCTBH.setEnabled(true);
        btnThem.setEnabled(true);
        showData1();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        btnThem1.setEnabled(false);
        btnSua1.setEnabled(true);
        baoloi.setText("");// TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtPBH.setText((String) jTable1.getValueAt(row, 1));
        txtMDH.setText((String) jTable1.getValueAt(row, 2));
        String datebd = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String datekt = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        //substring: trả lại chuỗi con vs [start;end)
        datebd = datebd.substring(0, 4) + "/" + datebd.substring(5, 7) + "/" + datebd.substring(8, 10);
        datekt = datekt.substring(0, 4) + "/" + datekt.substring(5, 7) + "/" + datekt.substring(8, 10);
        try {
            java.util.Date datetmp = new SimpleDateFormat("yyyy/MM/dd").parse(datebd);
            dateBD.setDate(datetmp);
            java.util.Date datetmp1 = new SimpleDateFormat("yyyy/MM/dd").parse(datekt);
            dateKT.setDate(datetmp1);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtPBH.setEnabled(false);

        if (evt.getClickCount() == 2) {
            jTable2.setDefaultEditor(Object.class, null);
            //jTable1.setSelectionBackground(Color.RED);
            jTable2.setSelectionMode(0);
            LayCT();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn phiếu bảo hành");
        } else if (txtPBH.getText().equals("") || txtMDH.getText().equals("") || dateBD.getDate().equals("") || dateKT.getDate().equals(""))
            baoloi.setText("Vui lòng nhập đầy đủ thông tin phiếu bảo hành!");
        else {

            txtPBH.setEnabled(false);
            int row = jTable1.getSelectedRow();

            PhieuBaoHanh bh = new PhieuBaoHanh(txtPBH.getText(), txtMDH.getText(), dateBD.getDate(), dateKT.getDate());

            if (jTable1.getSelectedRow() == -1) {
                for (PhieuBaoHanh bhh : Controller.controller.arrayListPhieuBaoHanh) {
                    if (bhh.getMaPBH().equals(txtPBH.getText())) {
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                }
                CONNECTION.InsertData.insertPhieuBaoHanh(bh);

                showData();

                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);

            } else {
                if (!check2(txtMDH.getText())) {
                    baoloi.setText("Mã đồng hồ không hợp lệ");
                    return;
                } else {
                    CONNECTION.UpdateData.updatePhieuBaoHanh(bh);
                }

            }
            String x = "";
            txtPBH.setText(x);
            txtMDH.setText(x);
            jTable1.setModel(myTable);
            dateBD.setDate(null);
            dateKT.setDate(null);
            btnThem1.setEnabled(true);
            jTable1.setModel(myTable);

            showData();
            jTable1.getSelectionModel().setSelectionInterval(row, row);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed
    }
    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        btnThem.setEnabled(false);
        txtCTBH.setEnabled(false);
        baoloi.setText("");// TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        txtCTBH.setText((String) jTable2.getValueAt(row, 1));
        txtTT.setText((String) jTable2.getValueAt(row, 2));
        txtMNV.setText((String) jTable2.getValueAt(row, 3));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (jTable2.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn chi tiết phiếu bảo hành");
        } else if (txtCTBH.getText().equals("") || txtTT.getText().equals("") || txtMNV.getText().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin chi tiết phiếu bảo hành!");
        } else {

            int row = jTable2.getSelectedRow();

            CT_PhieuBaoHanh ctph = new CT_PhieuBaoHanh(txtCTBH.getText(), txtTT.getText(), txtMNV.getText());
            if (jTable2.getSelectedRow() == -1) {

                for (CT_PhieuBaoHanh ctbh : Controller.controller.arrayListCT_PhieuBaoHanh) {
                    if (ctbh.getMaPBH().equals(txtCTBH.getText())) {
                        baoloi.setText("Mã bảo hành đã tồn tại!");
                        return;
                    }
                }
                CONNECTION.InsertData.insertCT_BaoHanh(ctph);

                showData1();

                jTable2.getSelectionModel().setSelectionInterval(jTable2.getRowCount() - 1, jTable2.getRowCount() - 1);

            } else {
                if (!check(txtCTBH.getText())) {
                    baoloi.setText("Mã bảo hành không hợp lệ");
                    return;
                } else if (!check1(txtMNV.getText())) {
                    baoloi.setText("Mã nhân viên không hợp lệ");
                    return;
                } else {
                    CONNECTION.UpdateData.updateCT_PhieuBaoHanh(ctph);
                }

            }
            showData1();
            jTable2.getSelectionModel().setSelectionInterval(row, row);
        }

        String y = "";
        txtCTBH.setText(y);
        txtMNV.setText(y);
        txtTT.setText(y);
        txtCTBH.setEnabled(true);
        jTable2.setModel(myTable1);
        btnThem.setEnabled(true);
        showData1();// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed

        Home home = new Home();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HomeActionPerformed
    public void showTheoNgayBD(String d1, String d2) {

        DataConnection.createStatement();
        try {
            String sql = ("select * from dbo.BaoHanh where NgayBD between ? and ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1, d1);
            ps.setString(2, d2);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while (rs.next()) {
                row = new Object[5];
                row[0] = dem++;
                row[1] = rs.getString("MaPBH");
                row[2] = rs.getString("MaDH");
                row[3] = rs.getDate("NgayBD");
                row[4] = rs.getDate("NgayKT");
                mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimActionPerformed

        jTable1.setModel(new DefaultTableModel(null, new Object[]{"STT", "Mã phiếu bảo hành", "Mã đồng hồ", "Ngày bắt đầu", "Ngày kết thúc"}));
        try {
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            String jdate = date.format(TuNgay.getDate());
            String jdate1 = date.format(DenNgay.getDate());

            showTheoNgayBD(jdate, jdate1);

        } catch (Exception ex) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_TimActionPerformed
    public void showHetHanBH(String d1) {
        DataConnection.createStatement();
        try {
            String sql = ("select * from dbo.BaoHanh where NgayKT < ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1, d1);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while (rs.next()) {
                row = new Object[5];
                row[0] = dem++;
                row[1] = rs.getString("MaPBH");
                row[2] = rs.getString("MaDH");
                row[3] = rs.getDate("NgayBD");
                row[4] = rs.getDate("NgayKT");
                mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"STT", "Mã phiếu bảo hành", "Mã đồng hồ", "Ngày bắt đầu", "Ngày kết thúc"}));
        try {
            long millis = System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            String time = date.toString();
            showHetHanBH(time);

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public void showConHanBH(String d1) {
        DataConnection.createStatement();
        try {
            String sql = ("select * from dbo.BaoHanh where NgayKT > ?");
            PreparedStatement ps = DataConnection.connection.prepareStatement(sql);
            ps.setString(1, d1);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel mode = (DefaultTableModel) jTable1.getModel();
            Object[] row;
            int dem = 1;
            while (rs.next()) {
                row = new Object[5];
                row[0] = dem++;
                row[1] = rs.getString("MaPBH");
                row[2] = rs.getString("MaDH");
                row[3] = rs.getDate("NgayBD");
                row[4] = rs.getDate("NgayKT");
                mode.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"STT", "Mã phiếu bảo hành", "Mã đồng hồ", "Ngày bắt đầu", "Ngày kết thúc"}));
        try {
            long millis = System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            String time = date.toString();
            showConHanBH(time);

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TuNgayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TuNgayAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TuNgayAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienBaoHanh BH = new GiaoDienBaoHanh();
                BH.setLocationRelativeTo(null);
                BH.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DenNgay;
    private javax.swing.JButton Tim;
    private com.toedter.calendar.JDateChooser TuNgay;
    private javax.swing.JLabel baoloi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btn_Home;
    private com.toedter.calendar.JDateChooser dateBD;
    private com.toedter.calendar.JDateChooser dateKT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel pnl_BH;
    private javax.swing.JPanel pnl_CTBH;
    private javax.swing.JTextField txtCTBH;
    private javax.swing.JTextField txtMDH;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextField txtPBH;
    private javax.swing.JTextArea txtTT;
    // End of variables declaration//GEN-END:variables
}
