/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;

import CONNECTION.DataConnection;
import CONNECTION.LoadData;
import Function.DigitsDocument;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.CT_PhieuDat;
import Model.HoaDon;
import Model.NhanVien;
import Model.PhieuDat;
import java.math.RoundingMode;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Admin
 */
public class GiaoDienHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienHoaDon
     */
    private DefaultTableModel myTable;
    private DefaultTableModel myTable3;

    public GiaoDienHoaDon() {
        initComponents();
        txtMaNV.setEnabled(false);
        txtTongTien.setEnabled(false);
        myTable = (DefaultTableModel) jTable1.getModel();
        showData();
        txtMSTHD.setDocument(new DigitsDocument());
        jTable1.setSelectionMode(0);
        txtMaNV.setText(Controller.controller.tk.getMaNV());
        txtMHD.setEnabled(false);
    }

    private void showData() {
        new LoadData();
        int dem = 1;

        myTable.setRowCount(0);
        for (HoaDon hd : Controller.controller.arrayListHoaDon) {

            BigDecimal Gia = new BigDecimal(hd.getThanhTien().toString());
            Gia = Gia.setScale(0, RoundingMode.HALF_UP);
            myTable.addRow(new Object[]{dem++, hd.getMaHD(), hd.getMaPD(), hd.getMSTHD(), hd.getNgayIn(), Gia, hd.getMaNV()});
        }
    }

    private String Tien(String MaPD) {
        String Gia2;
        long Gia0 = 0;
        GiaoDienPhieuDat PD = new GiaoDienPhieuDat();
        myTable3 = (DefaultTableModel) PD.tblCT_PhieuDat.getModel();

        for (int i = 0; i < PD.tblCT_PhieuDat.getRowCount(); i++) {
            String n = (String) myTable3.getValueAt(i, 1);
            if (n.equals(MaPD)) {
                BigDecimal GiaNe = new BigDecimal(PD.tblCT_PhieuDat.getValueAt(i, 4).toString());
                GiaNe = GiaNe.setScale(0, RoundingMode.HALF_UP);
                long Gia1 = Long.valueOf(GiaNe.toString());
                Gia0 = (Gia0 + Gia1);

            }

        }
        Gia2 = String.valueOf(Gia0);
        BigDecimal Gia3 = new BigDecimal(Gia2);
        String x = Gia3.toString();
        return x;

    }

    private boolean check(String Ma) {
        for (PhieuDat pd : Controller.controller.arrayListPhieuDat) {
            if ((pd.getMaPD().trim().equals(Ma.trim()))) {
                return true;

            }

        }
        return false;
    }

    private boolean check1(String Ma) {
        for (NhanVien nv : Controller.controller.arrayListNhanVien) {
            if ((nv.getMaNV().trim().equals(Ma.trim()))) {
                return true;

            }

        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnl_TTCT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        dateBan = new com.toedter.calendar.JDateChooser();
        txtMSTHD = new javax.swing.JTextField();
        txtMHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtPhieuDat = new javax.swing.JTextField();
        pnl_MH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        baoloi = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnl_BoLoc = new javax.swing.JPanel();
        txtTK = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HÓA ĐƠN");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 149, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HÓA ĐƠN BÁN HÀNG");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        pnl_TTCT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_TTCT.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã hóa đơn");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Tổng tiền");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ngày bán");

        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        dateBan.setDateFormatString("yyyy-MM-dd");

        txtMSTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMSTHDActionPerformed(evt);
            }
        });

        txtMHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMHDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MSTHD");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Thông tin chi tiết");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã phiếu đặt");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã nhân viên");

        txtPhieuDat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhieuDatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhieuDatKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_TTCTLayout = new javax.swing.GroupLayout(pnl_TTCT);
        pnl_TTCT.setLayout(pnl_TTCTLayout);
        pnl_TTCTLayout.setHorizontalGroup(
            pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TTCTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TTCTLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_TTCTLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_TTCTLayout.createSequentialGroup()
                                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(23, 23, 23)
                                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMHD, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(txtMaNV)))
                            .addGroup(pnl_TTCTLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateBan, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_TTCTLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addComponent(txtMSTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnl_TTCTLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPhieuDat))
                                .addGroup(pnl_TTCTLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(38, 38, 38)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))))
        );
        pnl_TTCTLayout.setVerticalGroup(
            pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TTCTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMSTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtPhieuDat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TTCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnl_MH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_MH.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(247, 220, 104));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hóa đơn", "Mã phiếu đặt", "MSTHD", "Ngày in", "Thành tiền", "Mã nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Close-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pen-Red-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Print-icon.png"))); // NOI18N
        btnIn.setText("Xuất hóa đơn");
        btnIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Danh sách mặt hàng");

        baoloi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        baoloi.setForeground(new java.awt.Color(244, 108, 63));
        baoloi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baoloi.setText("Thông báo:");

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset-icon.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bieu do.png"))); // NOI18N
        jButton1.setText("Biểu đồ doanh thu");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_MHLayout = new javax.swing.GroupLayout(pnl_MH);
        pnl_MH.setLayout(pnl_MHLayout);
        pnl_MHLayout.setHorizontalGroup(
            pnl_MHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pnl_MHLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnl_MHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_MHLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_MHLayout.setVerticalGroup(
            pnl_MHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baoloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_MHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnl_BoLoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_BoLoc.setForeground(new java.awt.Color(51, 51, 51));

        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/funnel-icon.png"))); // NOI18N
        jButton5.setText("Lọc");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Bộ lọc thông tin");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vui lòng nhập thông tin cần lọc vào ô trống");

        javax.swing.GroupLayout pnl_BoLocLayout = new javax.swing.GroupLayout(pnl_BoLoc);
        pnl_BoLoc.setLayout(pnl_BoLocLayout);
        pnl_BoLocLayout.setHorizontalGroup(
            pnl_BoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_BoLocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_BoLocLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_BoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnl_BoLocLayout.setVerticalGroup(
            pnl_BoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_BoLocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_BoLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_BoLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(home)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_MH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_TTCT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(home)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnl_TTCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_MH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_BoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMHDActionPerformed

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    private void txtMSTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMSTHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMSTHDActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if ( txtMSTHD.getText().equals("") || txtMaNV.getText().equals("") || txtPhieuDat.getText().equals("") || dateBan.getDate().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin nhân viên!");
        } else {
            BigDecimal Gia;
            int row = jTable1.getSelectedRow();

            BigDecimal T = new BigDecimal(Tien(txtPhieuDat.getText()));

            HoaDon hd = new HoaDon(txtMHD.getText(), txtMaNV.getText(), txtPhieuDat.getText(), txtMSTHD.getText(), T, dateBan.getDate());
            if (jTable1.getSelectedRow() == -1) {

                for (HoaDon hdd : Controller.controller.arrayListHoaDon) {
                    if (hdd.getMaHD().equals(txtMHD.getText())) {
                        baoloi.setText("Hóa đơn đã tồn tại!");
                        return;
                    }
                }
                if (!check(txtPhieuDat.getText())) {
                    baoloi.setText("Mã phiếu đặt không hợp lệ");
                    return;
                } else if (!check1(txtMaNV.getText())) {
                    baoloi.setText("Mã nhân viên không hợp lệ");
                    return;
                } else {
                    CONNECTION.InsertData.insertHoaDon(hd);
                }

                showData();

                jTable1.getSelectionModel().setSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);

            } else {

                CONNECTION.UpdateData.updateHoaDon(hd);

            }
            showData();
            jTable1.getSelectionModel().setSelectionInterval(row, row);
        }
        String x = "";
        txtMHD.setText(x);
        txtMSTHD.setText(x);
        txtMaNV.setText(x);
        txtPhieuDat.setText(x);
        txtTongTien.setText(x);
        dateBan.setDate(null);
        showData();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            baoloi.setText("Vui lòng chọn hóa đơn");
        } else {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Xác Nhận Xóa Hóa đơn?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                CONNECTION.DeleteData.deleteHoaDon((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                showData();
            }
        }
        String x = "";
        txtMHD.setText(x);
        txtMSTHD.setText(x);
        txtMaNV.setText(x);
        txtPhieuDat.setText(x);
        txtTongTien.setText(x);
        dateBan.setDate(null);
        btnThem.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        txtMHD.setEnabled(false);
        btnThem.setEnabled(false);

        baoloi.setText("");// TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txtMHD.setText((String) jTable1.getValueAt(row, 1));
        txtPhieuDat.setText((String) jTable1.getValueAt(row, 2));
        txtMSTHD.setText((String) jTable1.getValueAt(row, 3));
        String datein = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        txtTongTien.setText(jTable1.getValueAt(row, 5).toString());
        txtMaNV.setText((String) jTable1.getValueAt(row, 6));
        datein = datein.substring(8, 10) + "/" + datein.substring(5, 7) + "/" + datein.substring(0, 4);
        try {
            java.util.Date datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(datein);
            dateBan.setDate(datetmp);

        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTongTien.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        if (txtMHD.getText().equals("") || txtMSTHD.getText().equals("") || txtMaNV.getText().equals("") || txtPhieuDat.getText().equals("") || dateBan.getDate().equals("")) {
            baoloi.setText("Vui lòng nhập đầy đủ thông tin hóa đơn!");
        } else {
            BigDecimal Gia;
            int row = jTable1.getSelectedRow();
            for (CT_PhieuDat ctpd : Controller.controller.arrayListCT_PhieuDat) {
                if (ctpd.getMaPD().equals(txtPhieuDat.getText())) {
                    Gia = ctpd.getGia();
                    String Gia1 = Gia.toString();
                    txtTongTien.setText(Gia1);
                }
            }
            Gia = new BigDecimal(Tien(txtPhieuDat.getText()));
            String MSTHD = (String) jTable1.getValueAt(row, 3);

            HoaDon hd = new HoaDon(txtMHD.getText(), txtMaNV.getText(), txtPhieuDat.getText(), txtMSTHD.getText(), Gia, dateBan.getDate());
            for (HoaDon hdd : Controller.controller.arrayListHoaDon) {
                if ((txtMSTHD.getText().equals(hdd.getMSTHD())) && (!txtMSTHD.getText().equals(MSTHD))) {
                    baoloi.setText("MSTHD bị trùng");
                    return;
                }

            }
            if (!check(txtPhieuDat.getText())) {
                baoloi.setText("Mã phiếu đặt không hợp lệ");
                return;
            } else if (!check1(txtMaNV.getText())) {
                baoloi.setText("Mã nhân viên không hợp lệ");
                return;
            } else {
                CONNECTION.UpdateData.updateHoaDon(hd);
            }

        }

        baoloi.setText("Sửa thành công");
        String x = "";
        txtMHD.setText(x);
        txtMSTHD.setText(x);
        txtMaNV.setText(x);
        txtPhieuDat.setText(x);
        txtTongTien.setText(x);
        btnThem.setEnabled(true);
        dateBan.setDate(null);
        showData();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed

       GiaoDienXuatHoaDon Xuat = new GiaoDienXuatHoaDon(txtMHD.getText());
        Xuat.setLocationRelativeTo(null);
        Xuat.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnInActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String TK = txtTK.getText();
        TimKiem(TK);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        String x = "";
        txtMHD.setText(x);
        txtMSTHD.setText(x);
        txtMaNV.setText(x);
        txtPhieuDat.setText(x);
        txtTongTien.setText(x);
        btnThem.setEnabled(true);
        dateBan.setDate(null);
        showData();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed
//JDBCCategoryDataset:triển khai trên tập kết quả JDBC của cơ sở dữ liệu

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sql = "SELECT MONTH(NgayIn), SUM(ThanhTien/1000000) FROM HoaDon Group by month(NgayIn)";
            JDBCCategoryDataset data = new JDBCCategoryDataset(DataConnection.connection, sql);
            JFreeChart chart = ChartFactory.createLineChart("DOANH THU CỬA HÀNG", "Tháng", "Thành Tiền - (Triệu VND)",data, PlotOrientation.VERTICAL, false, true, true);
            ChartFrame frame = new ChartFrame("BIỂU ĐỒ DOANH THU", chart);
            frame.setVisible(true);
            frame.setSize(890, 760);
            frame.setLocationRelativeTo(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void TongTien(String MaPD){
    BigDecimal gia = BigDecimal.ZERO;

        for(CT_PhieuDat pd : Controller.controller.arrayListCT_PhieuDat){
            BigDecimal SLa = new BigDecimal(pd.getSoLuong());           
           if(MaPD.equals(pd.getMaPD().trim())){              
                gia = gia.add(pd.getGia());
            }
            txtTongTien.setText(gia.toString());
        }
    }
    private void txtPhieuDatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhieuDatKeyPressed
        

// TODO add your handling code here:
    }//GEN-LAST:event_txtPhieuDatKeyPressed

    private void txtPhieuDatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhieuDatKeyReleased
        for(CT_PhieuDat pd : Controller.controller.arrayListCT_PhieuDat){
            if(!pd.getMaPD().trim().equals(txtPhieuDat.getText().trim())){
                System.err.println("sai");
            }else{
                TongTien(txtPhieuDat.getText().trim());
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtPhieuDatKeyReleased
    private DefaultTableModel model;

    private void TimKiem(String Str) {
        model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(Str));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoDienHoaDon HD = new GiaoDienHoaDon();
                HD.setLocationRelativeTo(null);
                HD.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoloi;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser dateBan;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JPanel pnl_BoLoc;
    private javax.swing.JPanel pnl_MH;
    private javax.swing.JPanel pnl_TTCT;
    private javax.swing.JTextField txtMHD;
    private javax.swing.JTextField txtMSTHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtPhieuDat;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
